title: SoGrid 주식 노트
description: 나의 주식 투자 기록
remote_theme: just-the-docs/just-the-docs

url: "https://so-grid.github.io"
baseurl: ""

aux_links:
  GitHub Repository: https://github.com/so-grid/so-grid.github.io
